### ISSUE TITLE
Please remove this repository, because it's our company internal course

### ISSUE THREAD

**Issue by magmel48** [matiishyn/react-noter#1]

**Comment by matiishyn** [comment]
Hi
Thanks for pointing this out

I've removed everything taken from course: wireframes, server code
And left all staff that I've created

**Comment by magmel48** [comment]
Another employee can find your implementation. We have Gitlab for learning purposes.

**Comment by matiishyn** [comment]
There's no connection to the course.
Anyway my code it's not finished and I'm not removing it from here
